---
- name: Install essential packages on EC2
  hosts: all
  become: true
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
          - unzip
          - git
        state: present
        
    - name: Download JFrog artifact
      get_url:
       url: "{{ artifact_url }}"
       dest: "/opt/myapp/"
